Update release-creator.yaml

diff --git a/.github/workflows/release-creator.yaml b/.github/workflows/release-creator.yaml
--- a/.github/workflows/release-creator.yaml
+++ b/.github/workflows/release-creator.yaml
@@ -111,13 +111,17 @@ jobs:
       - name: Set file name
         shell: bash
         run: |
-          FILE=""
-          if [ -d "cert-csi-linux-amd64" ]; then
-              FILE="./cert-csi-linux-amd64/cert-csi-linux-amd64"
-          fi
+          set -euo pipefail
 
-          if [ -d "repctl-linux-amd64" ]; then
+          echo "Checking downloaded artifacts..."
+          FILE=""
+          if [ -f "./cert-csi-linux-amd64/cert-csi-linux-amd64" ]; then
+            FILE="./cert-csi-linux-amd64/cert-csi-linux-amd64"
+          elif [ -f "./repctl-linux-amd64/repctl-linux-amd64" ]; then
             FILE="./repctl-linux-amd64/repctl-linux-amd64"
+          else
+            echo "Binary file not found in expected locations."
+            exit 1
           fi
 
           echo "FILE_NAME=$FILE" >> $GITHUB_ENV
